### **Tratamento de dados de matrícula**

In [1]:
import pandas as pd

# Seleção das colunas de interesse para o DataFrame final
colunas_interesse = [
    'Instituição', 'Unidade de Ensino', 'Nome de Curso', 
    'Tipo de Curso', 'Turno', 'Cor / Raça', 
    'Sexo', 'Idade', 'Faixa Etária', 'Renda Familiar', 
    'Situação de Matrícula', 'Categoria da Situação',
    'Código do Ciclo Matricula',
    'Data de Inicio do Ciclo', 'Data de Fim Previsto do Ciclo',
    'Vagas Regulares l1', 'Vagas Regulares l2', 'Vagas Regulares l5', 
    'Vagas Regulares l6', 'Vagas Regulares l9', 'Vagas Regulares AC'
]

**Carga dos dados**

In [ ]:
chunks = pd.read_csv('../data/raw/microdados_matriculas_2023.csv', sep=';', encoding='utf-8', usecols=colunas_interesse, chunksize=50000)

tipos_graduacao = ['Licenciatura', 'Bacharelado', 'Tecnologia']

df_saida = pd.concat(
    [chunk[
        chunk['Instituição'].str.contains('BAHIA', na=False, case=False) &
        chunk['Tipo de Curso'].isin(tipos_graduacao)
    ] for chunk in chunks],
    ignore_index=True
)

# Remoção da coluna 'Instituição'
df_saida = df_saida.drop(columns=['Instituição'])
df_saida.to_csv('../data/processed/microdados_matriculas_2023_reduzido.csv', sep=';', encoding='utf-8', index=False)

In [ ]:
# Renomear colunas
df_saida.columns = [
    'categoria_situacao', 'cor_raca', 'codigo_ciclo_matricula',
    'data_fim_previsto_ciclo', 'data_inicio_ciclo', 'faixa_etaria',
    'idade', 'nome_curso', 'renda_familiar', 'sexo',
    'situacao_matricula', 'tipo_curso', 'turno', 'unidade_ensino',
    'vagas_regulares_ac', 'vagas_regulares_l1', 'vagas_regulares_l2',
    'vagas_regulares_l5', 'vagas_regulares_l6', 'vagas_regulares_l9'
]

,categoria_situacao,cor_raca,codigo_ciclo_matricula,data_fim_previsto_ciclo,data_inicio_ciclo,faixa_etaria,idade,nome_curso,renda_familiar,sexo,situacao_matricula,tipo_curso,turno,unidade_ensino,vagas_regulares_ac,vagas_regulares_l1,vagas_regulares_l2,vagas_regulares_l5,vagas_regulares_l6,vagas_regulares_l9
0,Em Curso,Parda,802715,12/07/2013,01/08/2011,45 a 49 anos,49,"Licenciatura para a Educação Profissional, Cie...","1<RFP<=1,5",M,Em curso,Licenciatura,Noturno,Campus Simões Filho,40.0,0.0,0.0,0.0,0.0,0.0
1,Evadidos,Preta,805360,08/03/2015,10/03/2011,30 a 34 anos,31,Matemática,Não declarada,F,Abandono,Licenciatura,Noturno,Campus Valença Tento,20.0,1.0,7.0,1.0,7.0,1.0
2,Em Curso,Branca,805366,30/12/2015,15/02/2011,30 a 34 anos,33,Engenharia Mecânica,Não declarada,M,Em curso,Bacharelado,Noturno,Campus Salvador,14.0,1.0,6.0,1.0,5.0,0.0
3,Em Curso,Não declarada,1209276,01/03/2017,01/03/2012,50 a 54 anos,50,Engenharia Elétrica,"2,5<RFP<=3,5",M,Em curso,Bacharelado,Noturno,Campus Paulo Afonso,20.0,2.0,6.0,2.0,10.0,0.0
4,Em Curso,Branca,1209276,01/03/2017,01/03/2012,30 a 34 anos,34,Engenharia Elétrica,"RFP>3,5",M,Em curso,Bacharelado,Noturno,Campus Paulo Afonso,20.0,2.0,6.0,2.0,10.0,0.0

Conversão do formato das datas de `string` para `datetime`

In [9]:
df_saida['data_inicio_ciclo'] = pd.to_datetime(df_saida['data_inicio_ciclo'], errors='coerce', dayfirst=True)
df_saida['data_fim_previsto_ciclo'] = pd.to_datetime(df_saida['data_fim_previsto_ciclo'], errors='coerce', dayfirst=True)
print(df_saida[['data_inicio_ciclo', 'data_fim_previsto_ciclo']].dtypes)

data_inicio_ciclo          datetime64[us]
data_fim_previsto_ciclo    datetime64[us]
dtype: object

Conversão do formato dos tipos de vagas de `float` para `int`

In [10]:
colunas_vagas = [
    'vagas_regulares_l1', 'vagas_regulares_l2', 'vagas_regulares_l5',
    'vagas_regulares_l6', 'vagas_regulares_l9', 'vagas_regulares_ac'
]
for col in colunas_vagas:
    df_saida[col] = pd.to_numeric(df_saida[col], errors='coerce').astype('Int64')

In [11]:
df_saida.info()

<class 'pandas.DataFrame'>
RangeIndex: 10034 entries, 0 to 10033
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   categoria_situacao       10034 non-null  str
 1   cor_raca                 10034 non-null  str
 2   codigo_ciclo_matricula   10034 non-null  int64
 3   data_fim_previsto_ciclo  10034 non-null  datetime64[us]
 4   data_inicio_ciclo        10034 non-null  datetime64[us]
 5   faixa_etaria             10034 non-null  str
 6   idade                    10034 non-null  int64
 7   nome_curso               10034 non-null  str
 8   renda_familiar           10034 non-null  str
 9   sexo                     10034 non-null  str
 10  situacao_matricula       10034 non-null  str
 11  tipo_curso               10034 non-null  str
 12  turno                    10034 non-null  str
 13  unidade_ensino           10034 non-null  str
 14  vagas_regulares_ac       9915 non-null   Int64
 15  vagas_regulares_l1       9915 non-null   Int64
 16  vagas_regulares_l2       9915 non-null   Int64
 17  vagas_regulares_l5       9915 non-null   Int64
 18  vagas_regulares_l6       9915 non-null   Int64
 19  vagas_regulares_l9       9915 non-null   Int64
dtypes: Int64(6), datetime64[us](2), int64(2), str(10)
memory usage: 1.6 MB

In [ ]:
# Exibir primeiras linhas do dataframe após tratamento inicial
df_saida.head()

,categoria_situacao,cor_raca,codigo_ciclo_matricula,data_fim_previsto_ciclo,data_inicio_ciclo,faixa_etaria,idade,nome_curso,renda_familiar,sexo,situacao_matricula,tipo_curso,turno,unidade_ensino,vagas_regulares_ac,vagas_regulares_l1,vagas_regulares_l2,vagas_regulares_l5,vagas_regulares_l6,vagas_regulares_l9
0,Em Curso,Parda,802715,2013-07-12,2011-08-01,45 a 49 anos,49,"Licenciatura para a Educação Profissional, Cie...","1<RFP<=1,5",M,Em curso,Licenciatura,Noturno,Campus Simões Filho,40,0,0,0,0,0
1,Evadidos,Preta,805360,2015-03-08,2011-03-10,30 a 34 anos,31,Matemática,Não declarada,F,Abandono,Licenciatura,Noturno,Campus Valença Tento,20,1,7,1,7,1
2,Em Curso,Branca,805366,2015-12-30,2011-02-15,30 a 34 anos,33,Engenharia Mecânica,Não declarada,M,Em curso,Bacharelado,Noturno,Campus Salvador,14,1,6,1,5,0
3,Em Curso,Não declarada,1209276,2017-03-01,2012-03-01,50 a 54 anos,50,Engenharia Elétrica,"2,5<RFP<=3,5",M,Em curso,Bacharelado,Noturno,Campus Paulo Afonso,20,2,6,2,10,0
4,Em Curso,Branca,1209276,2017-03-01,2012-03-01,30 a 34 anos,34,Engenharia Elétrica,"RFP>3,5",M,Em curso,Bacharelado,Noturno,Campus Paulo Afonso,20,2,6,2,10,0