### **EDA - Matrículas**

In [1]:
import pandas as pd
# Carregar o DataFrame tratado para análise exploratória
df_eda = pd.read_parquet('../data/processed/microdados_matriculas_tratados.parquet')

In [ ]:
# Visualizar os tipos de dados e informações gerais do DataFrame
df_eda.info()

<class 'pandas.DataFrame'>
RangeIndex: 10034 entries, 0 to 10033
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   categoria_situacao       10034 non-null  str
 1   cor_raca                 10034 non-null  str
 2   codigo_ciclo_matricula   10034 non-null  str
 3   data_fim_previsto_ciclo  10034 non-null  datetime64[us]
 4   data_inicio_ciclo        10034 non-null  datetime64[us]
 5   faixa_etaria             10034 non-null  str
 6   idade                    10034 non-null  int64
 7   nome_curso               10034 non-null  str
 8   renda_familiar           10034 non-null  str
 9   sexo                     10034 non-null  str
 10  situacao_matricula       10034 non-null  str
 11  tipo_curso               10034 non-null  str
 12  turno                    10034 non-null  str
 13  unidade_ensino           10034 non-null  str
 14  vagas_regulares_ac       9915 non-null   Int64
 15  vagas_regulares_l1       9915 non-null   Int64
 16  vagas_regulares_l2       9915 non-null   Int64
 17  vagas_regulares_l5       9915 non-null   Int64
 18  vagas_regulares_l6       9915 non-null   Int64
 19  vagas_regulares_l9       9915 non-null   Int64
dtypes: Int64(6), datetime64[us](2), int64(1), str(11)
memory usage: 2.7 MB

In [5]:
# Visualizar as primeiras linhas do DataFrame para verificar o conteúdo
df_eda.head(10)

,categoria_situacao,cor_raca,codigo_ciclo_matricula,data_fim_previsto_ciclo,data_inicio_ciclo,faixa_etaria,idade,nome_curso,renda_familiar,sexo,situacao_matricula,tipo_curso,turno,unidade_ensino,vagas_regulares_ac,vagas_regulares_l1,vagas_regulares_l2,vagas_regulares_l5,vagas_regulares_l6,vagas_regulares_l9
0,Em Curso,Parda,802715,2013-07-12,2011-08-01,45 a 49 anos,49,"Licenciatura para a Educação Profissional, Cie...","1<RFP<=1,5",M,Em curso,Licenciatura,Noturno,Campus Simões Filho,40,0,0,0,0,0
1,Evadidos,Preta,805360,2015-03-08,2011-03-10,30 a 34 anos,31,Matemática,Não declarada,F,Abandono,Licenciatura,Noturno,Campus Valença Tento,20,1,7,1,7,1
2,Em Curso,Branca,805366,2015-12-30,2011-02-15,30 a 34 anos,33,Engenharia Mecânica,Não declarada,M,Em curso,Bacharelado,Noturno,Campus Salvador,14,1,6,1,5,0
3,Em Curso,Não declarada,1209276,2017-03-01,2012-03-01,50 a 54 anos,50,Engenharia Elétrica,"2,5<RFP<=3,5",M,Em curso,Bacharelado,Noturno,Campus Paulo Afonso,20,2,6,2,10,0
4,Em Curso,Branca,1209276,2017-03-01,2012-03-01,30 a 34 anos,34,Engenharia Elétrica,"RFP>3,5",M,Em curso,Bacharelado,Noturno,Campus Paulo Afonso,20,2,6,2,10,0
5,Concluintes,Branca,1209283,2017-06-01,2012-06-01,30 a 34 anos,30,Engenharia Elétrica,"RFP>3,5",M,Integralizada,Bacharelado,Noturno,Campus Paulo Afonso,20,2,6,2,10,0
6,Concluintes,Parda,1209717,2016-03-28,2012-03-30,40 a 44 anos,43,Matemática,"0,5<RFP<=1",M,Integralizada,Licenciatura,Noturno,Campus Valença Tento,20,1,7,1,7,1
7,Concluintes,Parda,1251999,2015-12-18,2012-04-23,40 a 44 anos,41,"Licenciatura para a Educação Profissional, Cie...","2,5<RFP<=3,5",M,Integralizada,Licenciatura,Noturno,Campus Simões Filho,40,0,0,0,0,0
8,Concluídos,Não declarada,1254683,2015-12-30,2012-04-27,45 a 49 anos,47,Geografia,Não declarada,M,Concluída,Licenciatura,Noturno,Campus Salvador,15,2,4,2,4,0
9,Em Curso,Não declarada,1254683,2015-12-30,2012-04-27,50 a 54 anos,54,Geografia,Não declarada,M,Em curso,Licenciatura,Noturno,Campus Salvador,15,2,4,2,4,0

In [4]:
# Medidas estatísticas dos atributos numéricos
df_eda.describe()

,data_fim_previsto_ciclo,data_inicio_ciclo,idade,vagas_regulares_ac,vagas_regulares_l1,vagas_regulares_l2,vagas_regulares_l5,vagas_regulares_l6,vagas_regulares_l9
count,10034,10034,10034.000000,9915.0,9915.0,9915.0,9915.0,9915.0,9915.0
mean,2024-10-10 22:57:25.724536,2020-09-24 09:39:04.269483,28.754335,24.970146,1.886132,8.520928,1.779929,8.274937,0.561372
min,2013-07-12 00:00:00,2011-02-15 00:00:00,18.000000,0.0,0.0,0.0,-1.0,0.0,0.0
25%,2023-02-01 00:00:00,2019-04-22 00:00:00,22.000000,15.0,1.0,6.0,1.0,5.0,0.0
50%,2024-12-20 00:00:00,2021-02-08 00:00:00,26.000000,19.0,2.0,7.0,2.0,7.0,0.0
75%,2026-07-31 00:00:00,2022-08-08 00:00:00,33.000000,20.0,2.0,7.0,2.0,7.0,1.0
max,2029-12-31 00:00:00,2023-11-01 00:00:00,78.000000,204.0,14.0,56.0,17.0,56.0,8.0
std,NaN,NaN,8.904756,30.152834,1.62845,9.520586,1.626819,9.57217,1.524377

**Tratamento de valores ausentes**

In [6]:
# Detectar valores ausentes
df_eda.isna().sum()

categoria_situacao           0
cor_raca                     0
codigo_ciclo_matricula       0
data_fim_previsto_ciclo      0
data_inicio_ciclo            0
faixa_etaria                 0
idade                        0
nome_curso                   0
renda_familiar               0
sexo                         0
situacao_matricula           0
tipo_curso                   0
turno                        0
unidade_ensino               0
vagas_regulares_ac         119
vagas_regulares_l1         119
vagas_regulares_l2         119
vagas_regulares_l5         119
vagas_regulares_l6         119
vagas_regulares_l9         119
dtype: int64